### ISSUE TITLE
download files for jemx dummy requests

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-plugin-integral#17]
the find search didn't yield any results

**Comment by volodymyrss** [comment]
done?

**Comment by burnout87** [comment]
I cannot find on the server, rather only isgri ones, which ones should I look for?

**Comment by volodymyrss** [comment]
yesterday I uploaded in the same place, but now rather please look how they are used here:

https://github.com/oda-hub/dispatcher-plugin-integral/pull/20/files#diff-f4731c5b92b960285123c8bf9ca825f26f2e623756af26f0120e69645130870fR36

**Comment by burnout87** [comment]
I think the lightcurve fits files are still missing, both for jemx and isgri. Is that correct?
